AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  VerifySlip

  Sample SAM Template for VerifySlip

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  VerifySlipFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: verify_slip/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: 'arn:aws:iam::192479299400:role/service-role/ReadQRCode-role-6q1akagw'
      Environment:
        Variables:
          DATABASE: athena
          PORT: 5439
          USER: helloworld
          PASSWORD: wowpasswordissecure
          HOST: localhost
      Events:
        VerifySlip:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /verify-slip
            Method: POST
