version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - sam --help
#       - sam package --template-file ./CheckTransferRef/template.yaml --s3-bucket helloworld-sam-athena --output-template-file packaged-CheckTransferRef-template.yml
#       - sam package --template-file ./ConnectToRedshift/template.yaml --s3-bucket helloworld-sam-athena --output-template-file packaged-ConnectToRedshift-template.yml
#       - sam package --template-file ./GetImageFromS3/template.yaml --s3-bucket helloworld-sam-athena --output-template-file packaged-GetImageFromS3-template.yml
#       - sam package --template-file ./VerifySlip/template.yaml --s3-bucket helloworld-sam-athena --output-template-file packaged-VerifySlip-template.yml

# artifacts:
#     files:
#         - 'packaged-CheckTransferRef-template.yml'
#         - 'packaged-ConnectToRedshift-template.yml'
#         - 'packaged-GetImageFromS3-template.yml'
#         - 'packaged-VerifySlip-template.yml'