version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - pipenv run sam package --template-file ./CheckTransferRef/template.yaml --s3-bucket helloworld-sam-athena --output-template-file packaged-CheckTransferRef-template.yml
      - pipenv run sam package --template-file ./ConnectToRedshift/template.yaml --s3-bucket helloworld-sam-athena --output-template-file packaged-ConnectToRedshift-template.yml
      - pipenv run sam package --template-file ./GetImageFromS3/template.yaml --s3-bucket helloworld-sam-athena --output-template-file packaged-GetImageFromS3-template.yml

artifacts:
    files:
        - 'packaged-CheckTransferRef-template.yml'
        - 'packaged-ConnectToRedshift-template.yml'
        - 'packaged-GetImageFromS3-template.yml'